# LLM fine tuning for Qwen2.5-3B-Instruct

In [1]:
! pip uninstall -y torchao

Found existing installation: torchao 0.10.0
Uninstalling torchao-0.10.0:
  Successfully uninstalled torchao-0.10.0

In [2]:
! pip install trl

Collecting trl
  Downloading trl-1.8.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl) (1.14.0)
Collecting datasets>=4.7.0 (from trl)
  Downloading datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl) (26.2)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (5.13.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.11.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (1.23.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.29.7)
Collecting pyarrow>=21.0.0 (from datasets>=4.7.0->trl)
  Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2025.3.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.26.8)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.5.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2026.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.24.2)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->accelerate>=1.4.0->trl) (1.5.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=4.56.2->trl) (0.1.2)
Downloading trl-1.8.0-py3-none-any.whl (863 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 863.2/863.2 kB 22.7 MB/s eta 0:00:00
Downloading datasets-5.0.0-py3-none-any.whl (555 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 45.6 MB/s eta 0:00:00
Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (50.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 18.7 MB/s eta 0:00:00
Installing collected packages: pyarrow, datasets, trl
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
Successfully installed datasets-5.0.0 pyarrow-25.0.0 trl-1.8.0

In [3]:
"""
train_lora.py

LoRA fine-tuning of Qwen2.5-3B-Instruct on your generated Q&A dataset.
Designed to run in Google Colab (free tier, T4 GPU) as a single script
pasted into cells, or run top-to-bottom in one cell.

Uses full fp16/bf16 LoRA (no quantization) — fits on a T4 for a 3B model.

Expects train.jsonl and val.jsonl already uploaded to your Colab session
or Google Drive, in the chat-message format:
    {"messages": [{"role": "system", ...}, {"role": "user", ...}, {"role": "assistant", ...}]}
"""

# ============================================================
# CELL 1 — Install dependencies
# ============================================================
# Run this first in Colab (uncomment if running as a script directly):
#
# !pip install -q -U transformers accelerate peft trl datasets bitsandbytes
#
# Colab sometimes ships a torchao version that's incompatible with peft's
# import checks, causing:
#   ImportError: Found an incompatible version of torchao...
# Fix: remove it (LoRA/QLoRA here don't need it) — uncomment the line below.
#
# !pip uninstall -y torchao
#
# IMPORTANT: after running this cell, go to Runtime -> Restart runtime,
# then run all cells again from the top before proceeding.

# ============================================================
# CELL 2 — Mount Google Drive
# ============================================================
from google.colab import drive
drive.mount('/content/drive')

import os

# Where your train.jsonl / val.jsonl live. Adjust to wherever you put them
# (e.g. if you uploaded them straight to Drive under a project folder).
DATA_DIR = "/content/drive/MyDrive/llm-finetuning/dataset"
TRAIN_FILE = os.path.join(DATA_DIR, "train.jsonl")
VAL_FILE = os.path.join(DATA_DIR, "val.jsonl")

# Where the final LoRA adapter + tokenizer get saved on Drive
OUTPUT_DIR_DRIVE = "/content/drive/MyDrive/llm-finetuning/qwen2.5-3b-lora"

# Local scratch dir for checkpoints during training (faster than writing to Drive every step)
LOCAL_OUTPUT_DIR = "/content/qwen2.5-3b-lora-checkpoints"

os.makedirs(OUTPUT_DIR_DRIVE, exist_ok=True)
os.makedirs(LOCAL_OUTPUT_DIR, exist_ok=True)

# ============================================================
# CELL 3 — Imports
# ============================================================
import torch
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
)
from peft import LoraConfig, get_peft_model
from trl import SFTTrainer, SFTConfig

# ------------------------------------------------------------
# GPU CHECK — do this before anything else. If this prints False,
# STOP and go to Runtime -> Change runtime type -> T4 GPU, then
# re-run from the top. Training a 3B model on CPU is impractically
# slow (hours per step instead of seconds).
# ------------------------------------------------------------
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    raise RuntimeError(
        "No GPU detected! Go to Runtime -> Change runtime type -> "
        "Hardware accelerator -> T4 GPU, then re-run this notebook."
    )

# ============================================================
# CELL 4 — Config
# ============================================================
BASE_MODEL = "Qwen/Qwen2.5-3B-Instruct"

MAX_SEQ_LENGTH = 1024
NUM_EPOCHS = 3
LEARNING_RATE = 2e-4
PER_DEVICE_BATCH_SIZE = 2
GRAD_ACCUMULATION_STEPS = 8       # effective batch size = 2 * 8 = 16
SAVE_STEPS = 50                   # checkpoint frequency (protects against Colab disconnects)
LOGGING_STEPS = 10
EVAL_STEPS = 50

# ============================================================
# CELL 5 — Load dataset
# ============================================================
dataset = load_dataset(
    "json",
    data_files={"train": TRAIN_FILE, "validation": VAL_FILE},
)
print(dataset)
print("\nExample record:")
print(dataset["train"][0])

# ============================================================
# CELL 6 — Load tokenizer and model (fp16/bf16, no quantization)
# ============================================================
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    torch_dtype=torch.bfloat16,   # T4 supports bf16 compute fine for this size
    device_map="auto",
)
model.config.use_cache = False  # required for gradient checkpointing during training

# ============================================================
# CELL 7 — LoRA config
# ============================================================
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# ============================================================
# CELL 8 — Format function (applies the model's chat template)
# ============================================================
def formatting_func(example):
    text = tokenizer.apply_chat_template(
        example["messages"], tokenize=False, add_generation_prompt=False
    )
    return text

# ============================================================
# CELL 9 — Training arguments
# ============================================================
# NOTE: max sequence length is set via tokenizer.model_max_length below
# instead of an SFTConfig kwarg, since trl has renamed that argument
# across versions (max_seq_length vs max_length). This avoids the
# version mismatch entirely.
tokenizer.model_max_length = MAX_SEQ_LENGTH

sft_config = SFTConfig(
    output_dir=LOCAL_OUTPUT_DIR,
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=PER_DEVICE_BATCH_SIZE,
    per_device_eval_batch_size=PER_DEVICE_BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACCUMULATION_STEPS,
    gradient_checkpointing=True,
    learning_rate=LEARNING_RATE,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    logging_steps=LOGGING_STEPS,
    eval_strategy="steps",
    eval_steps=EVAL_STEPS,
    save_strategy="steps",
    save_steps=SAVE_STEPS,
    save_total_limit=3,
    bf16=True,
    packing=False,
    report_to="none",
)

# ============================================================
# CELL 10 — Trainer
# ============================================================
import inspect

trainer_params = set(inspect.signature(SFTTrainer.__init__).parameters.keys())
tokenizer_kwarg = "processing_class" if "processing_class" in trainer_params else "tokenizer"

trainer = SFTTrainer(
    model=model,
    args=sft_config,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
    formatting_func=formatting_func,
    **{tokenizer_kwarg: tokenizer},
)

# ============================================================
# CELL 11 — Train
# ============================================================
trainer.train()

# ============================================================
# CELL 12 — Save final model to Google Drive
# ============================================================
# Save LoRA adapter + tokenizer (small — a few hundred MB, not the full base model)
model.save_pretrained(OUTPUT_DIR_DRIVE)
tokenizer.save_pretrained(OUTPUT_DIR_DRIVE)

print(f"\nLoRA adapter saved to: {OUTPUT_DIR_DRIVE}")
print("Files:", os.listdir(OUTPUT_DIR_DRIVE))

# ============================================================
# OPTIONAL — also save the merged full model (base + adapter combined)
# Uncomment if you want a standalone model instead of an adapter.
# Note: this is much larger (~6GB) and takes extra time/memory to merge.
# ============================================================
# from peft import PeftModel
# merged_model = model.merge_and_unload()
# MERGED_OUTPUT_DIR = "/content/drive/MyDrive/llm-finetuning/qwen2.5-3b-lora-merged"
# os.makedirs(MERGED_OUTPUT_DIR, exist_ok=True)
# merged_model.save_pretrained(MERGED_OUTPUT_DIR)
# tokenizer.save_pretrained(MERGED_OUTPUT_DIR)
# print(f"Merged model saved to: {MERGED_OUTPUT_DIR}")

Mounted at /content/drive
CUDA available: True
GPU: Tesla T4

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['messages'],
        num_rows: 495
    })
    validation: Dataset({
        features: ['messages'],
        num_rows: 55
    })
})

Example record:
{'messages': [{'role': 'system', 'content': 'You are a helpful home-health assistant. You give general, safe, non-diagnostic guidance for common everyday illnesses. You always recommend seeing a doctor for severe, worsening, or unusual symptoms. You do not provide specific medication dosages or diagnose conditions.'}, {'role': 'user', 'content': 'What are some common causes of stomach ache and indigestion in adults, and how can I avoid them?'}, {'role': 'assistant', 'content': 'Common causes include eating too quickly, not chewing food properly, or consuming foods high in acidity, spice, or fat. Try eating slowly, avoiding trigger foods, and staying hydrated. If your symptoms worsen or last for an extended period, see a doctor.'}]}

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 29,933,568 || all params: 3,115,872,256 || trainable%: 0.9607

Applying formatting function to train dataset:   0%|          | 0/495 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/495 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/495 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/495 [00:00<?, ? examples/s]

Applying formatting function to eval dataset:   0%|          | 0/55 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/55 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/55 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/55 [00:00<?, ? examples/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

LoRA adapter saved to: /content/drive/MyDrive/llm-finetuning/qwen2.5-3b-lora
Files: ['README.md', 'adapter_model.safetensors', 'adapter_config.json', 'chat_template.jinja', 'tokenizer_config.json', 'tokenizer.json']

# LLM fine tuning for DeepSeek-R1-Distill-Qwen-7B

In [1]:
!pip install -U -q bitsandbytes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 19.1 MB/s eta 0:00:00

In [2]:
! pip install trl

Collecting trl
  Downloading trl-1.8.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl) (1.14.0)
Collecting datasets>=4.7.0 (from trl)
  Downloading datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl) (26.2)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (5.13.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.11.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (1.23.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.29.7)
Collecting pyarrow>=21.0.0 (from datasets>=4.7.0->trl)
  Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2025.3.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.26.8)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.5.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2026.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.24.2)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->accelerate>=1.4.0->trl) (1.5.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=4.56.2->trl) (0.1.2)
Downloading trl-1.8.0-py3-none-any.whl (863 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 863.2/863.2 kB 17.5 MB/s eta 0:00:00
Downloading datasets-5.0.0-py3-none-any.whl (555 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 38.9 MB/s eta 0:00:00
Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (50.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 15.9 MB/s eta 0:00:00
Installing collected packages: pyarrow, datasets, trl
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
Successfully installed datasets-5.0.0 pyarrow-25.0.0 trl-1.8.0

In [3]:
import bitsandbytes as bnb
print(bnb.__version__)

0.49.2

In [4]:
"""
train_qlora.py

QLoRA fine-tuning of DeepSeek-R1-Distill-Qwen-7B on your generated Q&A dataset.
Designed to run in Google Colab (free tier, T4 GPU) as a single script
pasted into cells, or run top-to-bottom in one cell.

Uses 4-bit quantization (QLoRA) — this is what makes a 7B model fit on a
free T4 (16GB). Mirrors train_lora.py's structure so the two are easy to
compare side by side.

Expects train.jsonl and val.jsonl already uploaded to Google Drive, in the
chat-message format:
    {"messages": [{"role": "system", ...}, {"role": "user", ...}, {"role": "assistant", ...}]}
"""

# ============================================================
# CELL 1 — Install dependencies
# ============================================================
# Run this first in Colab:
#
# !pip install -q -U transformers accelerate peft trl datasets bitsandbytes
#
# Colab sometimes ships a torchao version incompatible with peft's import
# checks (ImportError: Found an incompatible version of torchao...).
# LoRA/QLoRA here don't need torchao, so remove it if you hit that error:
#
# !pip uninstall -y torchao
#
# IMPORTANT: after running this cell (especially the uninstall line), go to
# Runtime -> Restart runtime, then run all cells again from the top.

# ============================================================
# CELL 2 — Mount Google Drive
# ============================================================
from google.colab import drive
drive.mount('/content/drive')

import os

# Where your train.jsonl / val.jsonl live.
DATA_DIR = "/content/drive/MyDrive/llm-finetuning/dataset"
TRAIN_FILE = os.path.join(DATA_DIR, "train.jsonl")
VAL_FILE = os.path.join(DATA_DIR, "val.jsonl")

# Where the final QLoRA adapter + tokenizer get saved on Drive
OUTPUT_DIR_DRIVE = "/content/drive/MyDrive/llm-finetuning/deepseek-r1-7b-qlora"

# Local scratch dir for checkpoints during training
LOCAL_OUTPUT_DIR = "/content/deepseek-r1-7b-qlora-checkpoints"

os.makedirs(OUTPUT_DIR_DRIVE, exist_ok=True)
os.makedirs(LOCAL_OUTPUT_DIR, exist_ok=True)

# ============================================================
# CELL 3 — Imports + GPU check
# ============================================================
import torch
import inspect
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig
from transformers import EarlyStoppingCallback

# GPU CHECK — do this before anything else. A 7B model, even 4-bit, is not
# practical on CPU. If this raises, go to Runtime -> Change runtime type ->
# Hardware accelerator -> T4 GPU, then re-run from the top.
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    raise RuntimeError(
        "No GPU detected! Go to Runtime -> Change runtime type -> "
        "Hardware accelerator -> T4 GPU, then re-run this notebook."
    )

# ============================================================
# CELL 4 — Config
# ============================================================
BASE_MODEL = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"

MAX_SEQ_LENGTH = 1024
NUM_EPOCHS = 3
LEARNING_RATE = 2e-4
PER_DEVICE_BATCH_SIZE = 1          # smaller than the LoRA script — 7B in 4-bit still needs headroom
GRAD_ACCUMULATION_STEPS = 16       # effective batch size = 1 * 16 = 16
SAVE_STEPS = 50
LOGGING_STEPS = 10
EVAL_STEPS = 50
EARLY_STOPPING_PATIENCE = 3        # stop if eval loss doesn't improve for 3 eval rounds in a row

# ============================================================
# CELL 5 — Load dataset
# ============================================================
dataset = load_dataset(
    "json",
    data_files={"train": TRAIN_FILE, "validation": VAL_FILE},
)
print(dataset)
print("\nExample record:")
print(dataset["train"][0])

# ============================================================
# CELL 6 — Load tokenizer and model in 4-bit (QLoRA)
# ============================================================
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    quantization_config=bnb_config,
    device_map="auto",
)
model.config.use_cache = False

# Required prep step for k-bit (4-bit) training — enables gradient checkpointing
# and casts certain layers appropriately for stable QLoRA training.
model = prepare_model_for_kbit_training(model)

# ============================================================
# CELL 7 — LoRA config (same target modules/rank as the LoRA script,
# so the two runs are a fair comparison)
# ============================================================
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# ============================================================
# CELL 8 — Format function (applies the model's chat template)
# ============================================================
def formatting_func(example):
    text = tokenizer.apply_chat_template(
        example["messages"], tokenize=False, add_generation_prompt=False
    )
    return text

# ============================================================
# CELL 9 — Training arguments
# ============================================================
# max sequence length is set via tokenizer.model_max_length rather than an
# SFTConfig kwarg, since trl has renamed that argument across versions.
tokenizer.model_max_length = MAX_SEQ_LENGTH

sft_config = SFTConfig(
    output_dir=LOCAL_OUTPUT_DIR,
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=PER_DEVICE_BATCH_SIZE,
    per_device_eval_batch_size=PER_DEVICE_BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACCUMULATION_STEPS,
    gradient_checkpointing=True,
    learning_rate=LEARNING_RATE,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    logging_steps=LOGGING_STEPS,
    eval_strategy="steps",
    eval_steps=EVAL_STEPS,
    save_strategy="steps",
    save_steps=SAVE_STEPS,
    save_total_limit=3,
    bf16=True,
    packing=False,
    report_to="none",
    load_best_model_at_end=True,       # needed for early stopping to restore the best checkpoint
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

# ============================================================
# CELL 10 — Trainer (with early stopping)
# ============================================================
# trl renamed the tokenizer argument to processing_class in newer versions.
# Detect which one this installed version expects.
trainer_params = set(inspect.signature(SFTTrainer.__init__).parameters.keys())
tokenizer_kwarg = "processing_class" if "processing_class" in trainer_params else "tokenizer"

trainer = SFTTrainer(
    model=model,
    args=sft_config,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
    formatting_func=formatting_func,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=EARLY_STOPPING_PATIENCE)],
    **{tokenizer_kwarg: tokenizer},
)

# ============================================================
# CELL 11 — Train
# ============================================================
trainer.train()

# ============================================================
# CELL 12 — Save final model to Google Drive
# ============================================================
# Saves the LoRA adapter only (small, a few hundred MB) — NOT the merged
# full model. This is the recommended default: the frozen 4-bit base model
# stays as-is, and only the small trained adapter needs to be saved/shared.
model.save_pretrained(OUTPUT_DIR_DRIVE)
tokenizer.save_pretrained(OUTPUT_DIR_DRIVE)

print(f"\nQLoRA adapter saved to: {OUTPUT_DIR_DRIVE}")
print("Files:", os.listdir(OUTPUT_DIR_DRIVE))

# ============================================================
# NOTE on merging for QLoRA
# ============================================================
# Merging a QLoRA adapter back into a full-precision model is possible but
# more involved than the plain-LoRA case (you can't simply merge into a
# 4-bit model — you'd need to reload the base model in fp16/bf16 first,
# then merge). Given free-tier Colab's limited RAM/VRAM, it's best to just
# keep the adapter and load it on top of the base model at inference time
# with peft's PeftModel.from_pretrained(), rather than merging.

Mounted at /content/drive
CUDA available: True
GPU: Tesla T4

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['messages'],
        num_rows: 495
    })
    validation: Dataset({
        features: ['messages'],
        num_rows: 55
    })
})

Example record:
{'messages': [{'role': 'system', 'content': 'You are a helpful home-health assistant. You give general, safe, non-diagnostic guidance for common everyday illnesses. You always recommend seeing a doctor for severe, worsening, or unusual symptoms. You do not provide specific medication dosages or diagnose conditions.'}, {'role': 'user', 'content': 'What are some common causes of stomach ache and indigestion in adults, and how can I avoid them?'}, {'role': 'assistant', 'content': 'Common causes include eating too quickly, not chewing food properly, or consuming foods high in acidity, spice, or fat. Try eating slowly, avoiding trigger foods, and staying hydrated. If your symptoms worsen or last for an extended period, see a doctor.'}]}

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/680 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/3.07k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/28.1k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 40,370,176 || all params: 7,655,986,688 || trainable%: 0.5273

Applying formatting function to train dataset:   0%|          | 0/495 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/495 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/495 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/495 [00:00<?, ? examples/s]

Applying formatting function to eval dataset:   0%|          | 0/55 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/55 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/55 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/55 [00:00<?, ? examples/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': 151646, 'pad_token_id': 151643}.

QLoRA adapter saved to: /content/drive/MyDrive/llm-finetuning/deepseek-r1-7b-qlora
Files: ['README.md', 'adapter_model.safetensors', 'adapter_config.json', 'chat_template.jinja', 'tokenizer_config.json', 'tokenizer.json']

# compare before after

In [1]:
!pip uninstall -y torchao

Found existing installation: torchao 0.10.0
Uninstalling torchao-0.10.0:
  Successfully uninstalled torchao-0.10.0

# LoRA before after

In [3]:
"""
compare_before_after.py

Loads a base model and your fine-tuned adapter (LoRA or QLoRA) on top of it,
then runs the same set of test questions through both so you can see exactly
what the fine-tuning changed. This is your main showcase artifact.

Run this in Colab, in its own fresh session (don't mix with a training run —
loading two copies of the model at once needs more VRAM than training alone).

Works for EITHER of your two fine-tunes — just set ADAPTER_TYPE below.
"""

# ============================================================
# CELL 1 — Install dependencies
# ============================================================
# !pip install -q -U transformers accelerate peft bitsandbytes
# !pip uninstall -y torchao   # uncomment if you hit the torchao ImportError again

# ============================================================
# CELL 2 — Mount Drive
# ============================================================
from google.colab import drive
drive.mount('/content/drive')

# ============================================================
# CELL 3 — Config — pick which fine-tune you're comparing
# ============================================================
# Set this to "lora" or "qlora" depending on which adapter you want to test.
ADAPTER_TYPE = "lora"   # change to "qlora" to test the other one

if ADAPTER_TYPE == "lora":
    BASE_MODEL = "Qwen/Qwen2.5-3B-Instruct"
    ADAPTER_PATH = "/content/drive/MyDrive/llm-finetuning/qwen2.5-3b-lora"
    USE_4BIT = False
elif ADAPTER_TYPE == "qlora":
    BASE_MODEL = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
    ADAPTER_PATH = "/content/drive/MyDrive/llm-finetuning/deepseek-r1-7b-qlora"
    USE_4BIT = True
else:
    raise ValueError("ADAPTER_TYPE must be 'lora' or 'qlora'")

SYSTEM_PROMPT = (
    "You are a helpful home-health assistant. You give general, safe, "
    "non-diagnostic guidance for common everyday illnesses. You always "
    "recommend seeing a doctor for severe, worsening, or unusual symptoms. "
    "You do not provide specific medication dosages or diagnose conditions."
)

# Test questions — mix of ones similar to your training topics AND a couple
# slightly different, to show the model generalizes rather than just
# memorizing exact training examples.
TEST_QUESTIONS = [
    "What should I do if I have a mild fever?",
    "My child has a wet cough, what can help?",
    "I have a pounding headache, any home remedies?",
    "How do I deal with a sore throat at home?",
    "What can I do about mild constipation?",
    "Is it normal to feel very tired with a cold?",  # slightly novel phrasing
]

MAX_NEW_TOKENS = 200

# ============================================================
# CELL 4 — Imports + GPU check
# ============================================================
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel

print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    raise RuntimeError("No GPU detected! Set Runtime -> T4 GPU before running.")

# ============================================================
# CELL 5 — Load tokenizer
# ============================================================
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# ============================================================
# CELL 6 — Load base model (used for the "before" answers)
# ============================================================
if USE_4BIT:
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
    )
    base_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL, quantization_config=bnb_config, device_map="auto"
    )
else:
    base_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL, torch_dtype=torch.bfloat16, device_map="auto"
    )

# ============================================================
# CELL 7 — Load the fine-tuned version (base + your adapter, for "after")
# ============================================================
finetuned_model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)

# ============================================================
# CELL 8 — Generation helper
# ============================================================
def generate_answer(model, question: str) -> str:
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": question},
    ]
    prompt = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            pad_token_id=tokenizer.pad_token_id,
        )

    generated = output_ids[0][inputs["input_ids"].shape[1]:]
    return tokenizer.decode(generated, skip_special_tokens=True).strip()

# ============================================================
# CELL 9 — Run comparison
# ============================================================
# IMPORTANT: to get a genuine "before" answer, we temporarily disable the
# adapter on the SAME model object (base_model and finetuned_model share
# the same underlying weights — finetuned_model just adds the adapter on
# top). Using .disable_adapter() avoids needing two separate model copies
# in memory, which matters on a free-tier T4.

results = []

for question in TEST_QUESTIONS:
    print(f"\n{'='*70}\nQ: {question}\n{'='*70}")

    with finetuned_model.disable_adapter():
        before_answer = generate_answer(finetuned_model, question)
    print(f"\n[BEFORE - base model]\n{before_answer}")

    after_answer = generate_answer(finetuned_model, question)
    print(f"\n[AFTER - fine-tuned]\n{after_answer}")

    results.append({
        "question": question,
        "before": before_answer,
        "after": after_answer,
    })

# ============================================================
# CELL 10 — Save results to Drive as a readable file
# ============================================================
import json

RESULTS_PATH = f"/content/drive/MyDrive/llm-finetuning/comparison_{ADAPTER_TYPE}.json"
with open(RESULTS_PATH, "w", encoding="utf-8") as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

print(f"\n\nSaved comparison results to: {RESULTS_PATH}")

# Also print a clean markdown-style summary you can paste straight into a
# README or portfolio writeup.
print("\n\n" + "="*70)
print("MARKDOWN SUMMARY (copy this into your README)")
print("="*70)
for r in results:
    print(f"\n**Q: {r['question']}**\n")
    print(f"- Before: {r['before']}\n")
    print(f"- After: {r['after']}\n")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
CUDA available: True
GPU: Tesla T4

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

======================================================================
Q: What should I do if I have a mild fever?
======================================================================

[BEFORE - base model]
If you have a mild fever, it's important to monitor your overall health and take some basic steps to feel better. Here’s what you can consider doing:

1. **Stay Hydrated**: Drink plenty of fluids like water, herbal teas (avoid those with caffeine), or clear broths to help prevent dehydration.

2. **Rest**: Give your body the chance to recover by getting adequate rest. Sleep is very beneficial when you're feeling unwell.

3. **Comfort Measures**: Use a cool compress on your forehead or take a lukewarm bath to help reduce your fever. Dress in light clothing.

4. **Over-the-Counter Medications**: You can use over-the-counter medications such as acetaminophen (Tylenol) or ibuprofen (Advil) to help manage the fever and any discomfort. Make sure to follow the dosage instructions carefully.

5. **Hydration and Nutrition**: Eat nutritious foods if you can. Sometimes bland, easy-to-digest foods

[AFTER - fine-tuned]
For a mild fever, try drinking plenty of fluids like water, tea, or clear broths to stay hydrated. You can also use a fever reducer or a pain reliever as directed on the label. Rest is also essential to help your body recover. If your fever persists beyond a few days or worsens over time, see a doctor.

======================================================================
Q: My child has a wet cough, what can help?
======================================================================

[BEFORE - base model]
A wet cough in children is often associated with conditions like bronchitis, pneumonia, or the common cold. Here are some general suggestions to help manage a wet cough:

1. **Stay Hydrated**: Encourage your child to drink plenty of fluids like water, herbal teas (like chamomile), or warm lemon water. This can help thin out mucus and make it easier to cough up.

2. **Humidifier**: Use a cool mist humidifier in your child's room to add moisture to the air, which can help ease breathing and reduce coughing.

3. **Rest**: Ensure your child gets plenty of rest, as this helps the body fight off illness more effectively.

4. **Gentle Chest Rubs**: You can use a mixture of one teaspoon of rubbing alcohol and one teaspoon of rubbing oil (like almond oil) to gently massage your child’s chest. This can help loosen phlegm and relieve congestion.

5. **Warm Compresses**:

[AFTER - fine-tuned]
For a wet cough in children, encourage them to drink plenty of fluids like water, clear broth, or electrolyte-rich beverages. You can also try using a humidifier to add moisture to the air and loosen up mucus. If your child's symptoms worsen or persist beyond a few days, or if you notice any warning signs like difficulty breathing or a fever over 102°F, seek medical attention.

======================================================================
Q: I have a pounding headache, any home remedies?
======================================================================

[BEFORE - base model]
Certainly! Here are some home remedies that might help alleviate your pounding headache:

1. **Rest**: Sometimes the best remedy is to simply rest in a quiet, dark room. This can help reduce stress on your body and mind.

2. **Hydration**: Make sure you drink plenty of water. Dehydration can sometimes cause headaches, so staying well-hydrated can be beneficial.

3. **Cold Compress**: Applying a cold compress to your forehead or neck can help reduce inflammation and numb the area, providing temporary relief.

4. **Warm Compress**: Alternatively, using a warm compress can help relax tense muscles in the head and neck.

5. **Over-the-Counter Pain Relievers**: Medications like ibuprofen, acetaminophen, or aspirin can help relieve pain. Always follow the dosage instructions on the label or as directed by a healthcare provider.

6. **Herbal Teas**: Drinking herbal teas like chamomile or peppermint can be soothing

[AFTER - fine-tuned]
Try taking a warm bath or using a heating pad on your forehead to help relax the muscles and reduce tension. Drinking plenty of fluids, such as water or clear broth, can also help alleviate symptoms. If your headache is severe or persists beyond a few days, it's best to consult with a doctor.

======================================================================
Q: How do I deal with a sore throat at home?
======================================================================

[BEFORE - base model]
Here are some tips to help manage a sore throat at home:

1. **Stay Hydrated**: Drink plenty of fluids like water, warm herbal tea (without sugar), or clear broths. Staying hydrated helps keep the throat moist and can ease discomfort.

2. **Humidify the Air**: Use a humidifier in your room to add moisture to the air. This can make breathing easier and soothe a sore throat.

3. **Warm Drinks**: Sip on warm liquids like lemon water with honey or warm herbal tea. Honey can be soothing and may also have antibacterial properties.

4. **Gargle with Salt Water**: Mix a teaspoon of salt in a cup of warm water and gargle gently. This can help reduce inflammation and relieve pain.

5. **Rest Your Throat**: Try to rest your voice as much as possible. Avoid talking too much and whispering can be tiring for your vocal cords.

6. **Use Over-the-Counter Medications

[AFTER - fine-tuned]
To help soothe a sore throat, try gargling with warm salt water, drinking plenty of fluids like water and warm liquids, and using a humidifier to add moisture to the air. You can also use throat lozenges or cough drops to temporarily relieve discomfort. If your symptoms worsen or last longer than a few days, see a doctor.

======================================================================
Q: What can I do about mild constipation?
======================================================================

[BEFORE - base model]
Mild constipation is quite common and can often be managed with simple lifestyle changes. Here are some tips that might help:

1. **Increase Fiber Intake**: Eat more fruits, vegetables, and whole grains. Fiber helps make your stools softer and easier to pass.

2. **Stay Hydrated**: Drink plenty of water throughout the day. Aim for at least 8 glasses of water daily.

3. **Exercise Regularly**: Physical activity can stimulate bowel movements. Try to engage in some form of exercise most days of the week.

4. **Establish a Routine**: Try to have bowel movements at the same time each day. This can help train your body to move waste regularly.

5. **Try Gentle Fiber Supplements**: If increasing fiber through diet alone isn't helping, you might consider using over-the-counter fiber supplements like psyllium husk or methylcellulose, following package instructions carefully.

6. **Avoid Diuretics and Heavy Beverages**: Reduce intake of caffeine,

[AFTER - fine-tuned]
Try drinking plenty of fluids, eating foods high in fiber like fruits and vegetables, and taking a gentle laxative as recommended by your doctor. If your symptoms persist or worsen, see a doctor for further advice. In the meantime, consider using a warm bath or a sitz bath to relax your muscles and promote bowel movements.

======================================================================
Q: Is it normal to feel very tired with a cold?
======================================================================

[BEFORE - base model]
It's quite common to feel very tired when you have a cold. Your body is working hard to fight off the virus, which can lead to fatigue. Other symptoms of a cold may include a runny or stuffy nose, sore throat, cough, headache, and sometimes a fever. As your immune system works to clear the infection, it can also make you feel very tired.

If you're generally feeling very fatigued despite resting and following self-care practices, it might be a good idea to consult a healthcare provider. They can help rule out other potential causes of your symptoms and ensure that your recovery is on track. Remember, staying hydrated, getting plenty of rest, and taking care of yourself can help you recover more quickly from a cold.

[AFTER - fine-tuned]
Yes, feeling very tired is a common symptom of a cold. Rest and staying hydrated can help you recover. If your symptoms persist beyond a few days or worsen, see a doctor for further advice.


Saved comparison results to: /content/drive/MyDrive/llm-finetuning/comparison_lora.json


======================================================================
MARKDOWN SUMMARY (copy this into your README)
======================================================================

**Q: What should I do if I have a mild fever?**

- Before: If you have a mild fever, it's important to monitor your overall health and take some basic steps to feel better. Here’s what you can consider doing:

1. **Stay Hydrated**: Drink plenty of fluids like water, herbal teas (avoid those with caffeine), or clear broths to help prevent dehydration.

2. **Rest**: Give your body the chance to recover by getting adequate rest. Sleep is very beneficial when you're feeling unwell.

3. **Comfort Measures**: Use a cool compress on your forehead or take a lukewarm bath to help reduce your fever. Dress in light clothing.

4. **Over-the-Counter Medications**: You can use over-the-counter medications such as acetaminophen (Tylenol) or ibuprofen (Advil) to help manage the fever and any discomfort. Make sure to follow the dosage instructions carefully.

5. **Hydration and Nutrition**: Eat nutritious foods if you can. Sometimes bland, easy-to-digest foods

- After: For a mild fever, try drinking plenty of fluids like water, tea, or clear broths to stay hydrated. You can also use a fever reducer or a pain reliever as directed on the label. Rest is also essential to help your body recover. If your fever persists beyond a few days or worsens over time, see a doctor.


**Q: My child has a wet cough, what can help?**

- Before: A wet cough in children is often associated with conditions like bronchitis, pneumonia, or the common cold. Here are some general suggestions to help manage a wet cough:

1. **Stay Hydrated**: Encourage your child to drink plenty of fluids like water, herbal teas (like chamomile), or warm lemon water. This can help thin out mucus and make it easier to cough up.

2. **Humidifier**: Use a cool mist humidifier in your child's room to add moisture to the air, which can help ease breathing and reduce coughing.

3. **Rest**: Ensure your child gets plenty of rest, as this helps the body fight off illness more effectively.

4. **Gentle Chest Rubs**: You can use a mixture of one teaspoon of rubbing alcohol and one teaspoon of rubbing oil (like almond oil) to gently massage your child’s chest. This can help loosen phlegm and relieve congestion.

5. **Warm Compresses**:

- After: For a wet cough in children, encourage them to drink plenty of fluids like water, clear broth, or electrolyte-rich beverages. You can also try using a humidifier to add moisture to the air and loosen up mucus. If your child's symptoms worsen or persist beyond a few days, or if you notice any warning signs like difficulty breathing or a fever over 102°F, seek medical attention.


**Q: I have a pounding headache, any home remedies?**

- Before: Certainly! Here are some home remedies that might help alleviate your pounding headache:

1. **Rest**: Sometimes the best remedy is to simply rest in a quiet, dark room. This can help reduce stress on your body and mind.

2. **Hydration**: Make sure you drink plenty of water. Dehydration can sometimes cause headaches, so staying well-hydrated can be beneficial.

3. **Cold Compress**: Applying a cold compress to your forehead or neck can help reduce inflammation and numb the area, providing temporary relief.

4. **Warm Compress**: Alternatively, using a warm compress can help relax tense muscles in the head and neck.

5. **Over-the-Counter Pain Relievers**: Medications like ibuprofen, acetaminophen, or aspirin can help relieve pain. Always follow the dosage instructions on the label or as directed by a healthcare provider.

6. **Herbal Teas**: Drinking herbal teas like chamomile or peppermint can be soothing

- After: Try taking a warm bath or using a heating pad on your forehead to help relax the muscles and reduce tension. Drinking plenty of fluids, such as water or clear broth, can also help alleviate symptoms. If your headache is severe or persists beyond a few days, it's best to consult with a doctor.


**Q: How do I deal with a sore throat at home?**

- Before: Here are some tips to help manage a sore throat at home:

1. **Stay Hydrated**: Drink plenty of fluids like water, warm herbal tea (without sugar), or clear broths. Staying hydrated helps keep the throat moist and can ease discomfort.

2. **Humidify the Air**: Use a humidifier in your room to add moisture to the air. This can make breathing easier and soothe a sore throat.

3. **Warm Drinks**: Sip on warm liquids like lemon water with honey or warm herbal tea. Honey can be soothing and may also have antibacterial properties.

4. **Gargle with Salt Water**: Mix a teaspoon of salt in a cup of warm water and gargle gently. This can help reduce inflammation and relieve pain.

5. **Rest Your Throat**: Try to rest your voice as much as possible. Avoid talking too much and whispering can be tiring for your vocal cords.

6. **Use Over-the-Counter Medications

- After: To help soothe a sore throat, try gargling with warm salt water, drinking plenty of fluids like water and warm liquids, and using a humidifier to add moisture to the air. You can also use throat lozenges or cough drops to temporarily relieve discomfort. If your symptoms worsen or last longer than a few days, see a doctor.


**Q: What can I do about mild constipation?**

- Before: Mild constipation is quite common and can often be managed with simple lifestyle changes. Here are some tips that might help:

1. **Increase Fiber Intake**: Eat more fruits, vegetables, and whole grains. Fiber helps make your stools softer and easier to pass.

2. **Stay Hydrated**: Drink plenty of water throughout the day. Aim for at least 8 glasses of water daily.

3. **Exercise Regularly**: Physical activity can stimulate bowel movements. Try to engage in some form of exercise most days of the week.

4. **Establish a Routine**: Try to have bowel movements at the same time each day. This can help train your body to move waste regularly.

5. **Try Gentle Fiber Supplements**: If increasing fiber through diet alone isn't helping, you might consider using over-the-counter fiber supplements like psyllium husk or methylcellulose, following package instructions carefully.

6. **Avoid Diuretics and Heavy Beverages**: Reduce intake of caffeine,

- After: Try drinking plenty of fluids, eating foods high in fiber like fruits and vegetables, and taking a gentle laxative as recommended by your doctor. If your symptoms persist or worsen, see a doctor for further advice. In the meantime, consider using a warm bath or a sitz bath to relax your muscles and promote bowel movements.


**Q: Is it normal to feel very tired with a cold?**

- Before: It's quite common to feel very tired when you have a cold. Your body is working hard to fight off the virus, which can lead to fatigue. Other symptoms of a cold may include a runny or stuffy nose, sore throat, cough, headache, and sometimes a fever. As your immune system works to clear the infection, it can also make you feel very tired.

If you're generally feeling very fatigued despite resting and following self-care practices, it might be a good idea to consult a healthcare provider. They can help rule out other potential causes of your symptoms and ensure that your recovery is on track. Remember, staying hydrated, getting plenty of rest, and taking care of yourself can help you recover more quickly from a cold.

- After: Yes, feeling very tired is a common symptom of a cold. Rest and staying hydrated can help you recover. If your symptoms persist beyond a few days or worsen, see a doctor for further advice.

# QLoRA before after

In [1]:
!pip install -U bitsandbytes>=0.46.1

In [2]:
"""
compare_before_after.py

Loads a base model and your fine-tuned adapter (LoRA or QLoRA) on top of it,
then runs the same set of test questions through both so you can see exactly
what the fine-tuning changed. This is your main showcase artifact.

Run this in Colab, in its own fresh session (don't mix with a training run —
loading two copies of the model at once needs more VRAM than training alone).

Works for EITHER of your two fine-tunes — just set ADAPTER_TYPE below.
"""

# ============================================================
# CELL 1 — Install dependencies
# ============================================================
# !pip install -q -U transformers accelerate peft bitsandbytes
# !pip uninstall -y torchao   # uncomment if you hit the torchao ImportError again

# ============================================================
# CELL 2 — Mount Drive
# ============================================================
from google.colab import drive
drive.mount('/content/drive')

# ============================================================
# CELL 3 — Config — pick which fine-tune you're comparing
# ============================================================
# Set this to "lora" or "qlora" depending on which adapter you want to test.
ADAPTER_TYPE = "qlora"   # change to "qlora" to test the other one

if ADAPTER_TYPE == "lora":
    BASE_MODEL = "Qwen/Qwen2.5-3B-Instruct"
    ADAPTER_PATH = "/content/drive/MyDrive/llm-finetuning/qwen2.5-3b-lora"
    USE_4BIT = False
elif ADAPTER_TYPE == "qlora":
    BASE_MODEL = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
    ADAPTER_PATH = "/content/drive/MyDrive/llm-finetuning/deepseek-r1-7b-qlora"
    USE_4BIT = True
else:
    raise ValueError("ADAPTER_TYPE must be 'lora' or 'qlora'")

SYSTEM_PROMPT = (
    "You are a helpful home-health assistant. You give general, safe, "
    "non-diagnostic guidance for common everyday illnesses. You always "
    "recommend seeing a doctor for severe, worsening, or unusual symptoms. "
    "You do not provide specific medication dosages or diagnose conditions."
)

# Test questions — mix of ones similar to your training topics AND a couple
# slightly different, to show the model generalizes rather than just
# memorizing exact training examples.
TEST_QUESTIONS = [
    "What should I do if I have a mild fever?",
    "My child has a wet cough, what can help?",
    "I have a pounding headache, any home remedies?",
    "How do I deal with a sore throat at home?",
    "What can I do about mild constipation?",
    "Is it normal to feel very tired with a cold?",  # slightly novel phrasing
]

MAX_NEW_TOKENS = 200

# ============================================================
# CELL 4 — Imports + GPU check
# ============================================================
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel

print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    raise RuntimeError("No GPU detected! Set Runtime -> T4 GPU before running.")

# ============================================================
# CELL 5 — Load tokenizer
# ============================================================
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# ============================================================
# CELL 6 — Load base model (used for the "before" answers)
# ============================================================
if USE_4BIT:
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
    )
    base_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL, quantization_config=bnb_config, device_map="auto"
    )
else:
    base_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL, torch_dtype=torch.bfloat16, device_map="auto"
    )

# ============================================================
# CELL 7 — Load the fine-tuned version (base + your adapter, for "after")
# ============================================================
finetuned_model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)

# ============================================================
# CELL 8 — Generation helper
# ============================================================
def generate_answer(model, question: str) -> str:
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": question},
    ]
    prompt = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            pad_token_id=tokenizer.pad_token_id,
        )

    generated = output_ids[0][inputs["input_ids"].shape[1]:]
    return tokenizer.decode(generated, skip_special_tokens=True).strip()

# ============================================================
# CELL 9 — Run comparison
# ============================================================
# IMPORTANT: to get a genuine "before" answer, we temporarily disable the
# adapter on the SAME model object (base_model and finetuned_model share
# the same underlying weights — finetuned_model just adds the adapter on
# top). Using .disable_adapter() avoids needing two separate model copies
# in memory, which matters on a free-tier T4.

results = []

for question in TEST_QUESTIONS:
    print(f"\n{'='*70}\nQ: {question}\n{'='*70}")

    with finetuned_model.disable_adapter():
        before_answer = generate_answer(finetuned_model, question)
    print(f"\n[BEFORE - base model]\n{before_answer}")

    after_answer = generate_answer(finetuned_model, question)
    print(f"\n[AFTER - fine-tuned]\n{after_answer}")

    results.append({
        "question": question,
        "before": before_answer,
        "after": after_answer,
    })

# ============================================================
# CELL 10 — Save results to Drive as a readable file
# ============================================================
import json

RESULTS_PATH = f"/content/drive/MyDrive/llm-finetuning/comparison_{ADAPTER_TYPE}.json"
with open(RESULTS_PATH, "w", encoding="utf-8") as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

print(f"\n\nSaved comparison results to: {RESULTS_PATH}")

# Also print a clean markdown-style summary you can paste straight into a
# README or portfolio writeup.
print("\n\n" + "="*70)
print("MARKDOWN SUMMARY (copy this into your README)")
print("="*70)
for r in results:
    print(f"\n**Q: {r['question']}**\n")
    print(f"- Before: {r['before']}\n")
    print(f"- After: {r['after']}\n")

Mounted at /content/drive
CUDA available: True
GPU: Tesla T4

config.json:   0%|          | 0.00/680 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/3.07k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/28.1k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

======================================================================
Q: What should I do if I have a mild fever?
======================================================================

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

[BEFORE - base model]
Okay, so I have a mild fever, and I'm not sure what to do. I remember hearing that fevers can be caused by many things, but I'm not exactly a medical expert. Let me think through this step by step.

First, what causes a mild fever? I think it could be a virus, maybe the flu, or perhaps something else. I've heard that a slight fever isn't necessarily a sign of a serious illness. But I'm not entirely sure. Maybe it's just a common cold or something like that.

I should consider the symptoms alongside the fever. Do I have any other symptoms like a cough, runny nose, sore throat, or maybe fatigue? If I do, that might help determine what's going on. But since I'm only experiencing a mild fever, maybe it's just a minor infection.

What should I do about the fever itself? I don't want to take unnecessary medications. I know that acetaminophen or ibuprofen

[AFTER - fine-tuned]
For a mild fever, try resting, drinking plenty of fluids, and using a fever reducer or antihistamine as directed. If your fever is severe, lasts longer than 3-4 days, or is accompanied by signs of dehydration, difficulty breathing, or severe pain, seek medical attention. Always follow the recommended dosage and consult with a doctor before giving medication to children.

======================================================================
Q: My child has a wet cough, what can help?
======================================================================

[BEFORE - base model]
Okay, so my child has a wet cough, and I'm trying to figure out what can help. I remember when my kids were young, coughing was pretty common, especially after playing outside or getting a cold. But now, I'm not exactly sure what's causing this or how to treat it. Let me think through this step by step.

First, what causes a wet cough? I know that coughing is the body's way of clearing out mucus, so sometimes it's just from a cold or allergies. But when it's wet, that usually means there's more mucus. So possible causes could be colds, allergies, bronchitis, pneumonia, or even something more serious like a fungal infection or asthma. I should consider all these possibilities.

I should start by assessing the situation. Is the cough worse at night or during the day? If it's worse at night, maybe it's related to asthma or allergies. If it's worse after coughing, that

[AFTER - fine-tuned]
For a wet cough in children, try using a humidifier to add moisture to the air, which can help soothe the throat. You can also try using a neti pot to rinse out the nasal passages with saline solution. If your child's cough is severe or lasts for an extended period, see a doctor for further guidance. Additionally, if you notice signs of a fever, difficulty breathing, or blood, seek medical attention right away.

======================================================================
Q: I have a pounding headache, any home remedies?
======================================================================

[BEFORE - base model]
Okay, so I have a pounding headache, and I'm looking for some home remedies. Let me think about what I know and what I can do. First, I remember that headaches can come from various things like dehydration, stress, lack of sleep, tension, or even sinus issues. I should consider different approaches to see what might help.

Hydration is something I've heard about before. Sometimes when I'm dehydrated, my brain gets extra stressed, leading to headaches. Maybe drinking water could help. But I should make sure I'm drinking enough throughout the day, not just before a headache hits.

Sunlight might be another option. I've heard that bright light can help with headaches, especially if they're tension headaches. Maybe sitting outside on a sunny day and reading or doing some light activities could help. But I need to be careful not to overexpose myself to the sun, as that could be harmful.

Rest is important too. If I'm feeling fatigued,

[AFTER - fine-tuned]
For a pounding headache, try resting in a quiet, dark room, drinking plenty of fluids, and taking a warm bath or using a heating pad. You can also try taking a pain reliever like acetaminophen or ibuprofen, but always follow the recommended dosage and consult a doctor if you're unsure. If your headache is severe, lasts more than a few days, or is accompanied by other concerning symptoms like nausea, vomiting, or difficulty breathing, seek medical attention immediately.

======================================================================
Q: How do I deal with a sore throat at home?
======================================================================

[BEFORE - base model]
Okay, so I need to figure out how to deal with a sore throat at home. I remember the assistant mentioned that I shouldn't worry unless my symptoms get worse or are unusual. But I'm here because I do have a sore throat, so let's think through the possible steps.

First, I should probably understand what causes a sore throat. I know that viruses, bacteria, and maybe even some parasites can cause sore throats. But I'm not sure which ones specifically. Maybe it's something like the flu or COVID-19? I think COVID-19 can cause a sore throat, but I'm not certain.

The assistant suggested using over-the-counter (OTC) medications. I know there are options like Motrin or Advil. I'm not sure which one is better. Maybe both can help, but I should consider what each one does. Motrin is an NSAID, so it might help with inflammation. Advil is a corticosteroid, which

[AFTER - fine-tuned]
To help alleviate a sore throat, try drinking warm liquids like tea or broth, and gargling with salt water. You can also use a humidifier to add moisture to the air, and use a throat lozenge or neti pot to soothe the throat. If your sore throat persists or is severe, see a doctor.

======================================================================
Q: What can I do about mild constipation?
======================================================================

[BEFORE - base model]
Okay, so I'm trying to figure out what to do about mild constipation. I remember the assistant mentioned some things, but I want to make sure I understand each step properly. First, the assistant said to start with dietary changes. That makes sense because fiber is important for digestion. I should probably increase my intake of fruits and vegetables. Fruits like bananas, berries, and oranges are high in fiber. Vegetables like broccoli, spinach, and cucumbers also have a lot of fiber. Maybe I can add some fiber supplements if I don't feel enough from my diet alone.

Next, the assistant suggested staying hydrated. I think drinking plenty of water is crucial, but sometimes I forget to drink enough. Maybe I can set a goal to drink 8 glasses a day. I also heard that water helps soften stools, so that's a good point. I should also avoid carbonated drinks and caffeine because they can make stools harder. I usually drink a lot of coffee, so

[AFTER - fine-tuned]
For mild constipation, try drinking plenty of fluids, eating a balanced diet rich in fiber, and exercising regularly. You can also try taking a stool softener or a fiber supplement to help relieve constipation. If your symptoms persist or worsen, or if you experience severe abdominal pain, blood in your stool, or difficulty breathing, seek medical attention.

======================================================================
Q: Is it normal to feel very tired with a cold?
======================================================================

[BEFORE - base model]
Okay, so I'm feeling really tired with a cold. I'm not sure if it's normal, but I want to figure this out. Let me think about how my cold is acting. I have a stuffy nose, maybe a little runny nose, and my throat feels a bit scratchy. I'm not sneezing much, but I do have a little cough sometimes. My energy level is dropping, and I'm not sleeping as well as I should. I feel like I'm just floating around all the time.

Hmm, when I get a cold, usually I feel better within a few days, right? But this time, I'm feeling worse. Maybe my body is fighting off the cold, but it's also getting me down. I wonder if it's the same for others. I've heard people say they feel really tired during flu season, but I'm not sure if that's the same as getting a cold.

I should consider other factors. Am I eating

[AFTER - fine-tuned]
Yes, it's quite common to feel very tired when you have a cold. Your body's main concern is fighting off the virus, and it can take a toll on your energy levels. Rest, fluids, and a good sleep can help you get through the fatigue. If you're still feeling very tired or experiencing other concerning symptoms, don't hesitate to see a doctor.


Saved comparison results to: /content/drive/MyDrive/llm-finetuning/comparison_qlora.json


======================================================================
MARKDOWN SUMMARY (copy this into your README)
======================================================================

**Q: What should I do if I have a mild fever?**

- Before: Okay, so I have a mild fever, and I'm not sure what to do. I remember hearing that fevers can be caused by many things, but I'm not exactly a medical expert. Let me think through this step by step.

First, what causes a mild fever? I think it could be a virus, maybe the flu, or perhaps something else. I've heard that a slight fever isn't necessarily a sign of a serious illness. But I'm not entirely sure. Maybe it's just a common cold or something like that.

I should consider the symptoms alongside the fever. Do I have any other symptoms like a cough, runny nose, sore throat, or maybe fatigue? If I do, that might help determine what's going on. But since I'm only experiencing a mild fever, maybe it's just a minor infection.

What should I do about the fever itself? I don't want to take unnecessary medications. I know that acetaminophen or ibuprofen

- After: For a mild fever, try resting, drinking plenty of fluids, and using a fever reducer or antihistamine as directed. If your fever is severe, lasts longer than 3-4 days, or is accompanied by signs of dehydration, difficulty breathing, or severe pain, seek medical attention. Always follow the recommended dosage and consult with a doctor before giving medication to children.


**Q: My child has a wet cough, what can help?**

- Before: Okay, so my child has a wet cough, and I'm trying to figure out what can help. I remember when my kids were young, coughing was pretty common, especially after playing outside or getting a cold. But now, I'm not exactly sure what's causing this or how to treat it. Let me think through this step by step.

First, what causes a wet cough? I know that coughing is the body's way of clearing out mucus, so sometimes it's just from a cold or allergies. But when it's wet, that usually means there's more mucus. So possible causes could be colds, allergies, bronchitis, pneumonia, or even something more serious like a fungal infection or asthma. I should consider all these possibilities.

I should start by assessing the situation. Is the cough worse at night or during the day? If it's worse at night, maybe it's related to asthma or allergies. If it's worse after coughing, that

- After: For a wet cough in children, try using a humidifier to add moisture to the air, which can help soothe the throat. You can also try using a neti pot to rinse out the nasal passages with saline solution. If your child's cough is severe or lasts for an extended period, see a doctor for further guidance. Additionally, if you notice signs of a fever, difficulty breathing, or blood, seek medical attention right away.


**Q: I have a pounding headache, any home remedies?**

- Before: Okay, so I have a pounding headache, and I'm looking for some home remedies. Let me think about what I know and what I can do. First, I remember that headaches can come from various things like dehydration, stress, lack of sleep, tension, or even sinus issues. I should consider different approaches to see what might help.

Hydration is something I've heard about before. Sometimes when I'm dehydrated, my brain gets extra stressed, leading to headaches. Maybe drinking water could help. But I should make sure I'm drinking enough throughout the day, not just before a headache hits.

Sunlight might be another option. I've heard that bright light can help with headaches, especially if they're tension headaches. Maybe sitting outside on a sunny day and reading or doing some light activities could help. But I need to be careful not to overexpose myself to the sun, as that could be harmful.

Rest is important too. If I'm feeling fatigued,

- After: For a pounding headache, try resting in a quiet, dark room, drinking plenty of fluids, and taking a warm bath or using a heating pad. You can also try taking a pain reliever like acetaminophen or ibuprofen, but always follow the recommended dosage and consult a doctor if you're unsure. If your headache is severe, lasts more than a few days, or is accompanied by other concerning symptoms like nausea, vomiting, or difficulty breathing, seek medical attention immediately.


**Q: How do I deal with a sore throat at home?**

- Before: Okay, so I need to figure out how to deal with a sore throat at home. I remember the assistant mentioned that I shouldn't worry unless my symptoms get worse or are unusual. But I'm here because I do have a sore throat, so let's think through the possible steps.

First, I should probably understand what causes a sore throat. I know that viruses, bacteria, and maybe even some parasites can cause sore throats. But I'm not sure which ones specifically. Maybe it's something like the flu or COVID-19? I think COVID-19 can cause a sore throat, but I'm not certain.

The assistant suggested using over-the-counter (OTC) medications. I know there are options like Motrin or Advil. I'm not sure which one is better. Maybe both can help, but I should consider what each one does. Motrin is an NSAID, so it might help with inflammation. Advil is a corticosteroid, which

- After: To help alleviate a sore throat, try drinking warm liquids like tea or broth, and gargling with salt water. You can also use a humidifier to add moisture to the air, and use a throat lozenge or neti pot to soothe the throat. If your sore throat persists or is severe, see a doctor.


**Q: What can I do about mild constipation?**

- Before: Okay, so I'm trying to figure out what to do about mild constipation. I remember the assistant mentioned some things, but I want to make sure I understand each step properly. First, the assistant said to start with dietary changes. That makes sense because fiber is important for digestion. I should probably increase my intake of fruits and vegetables. Fruits like bananas, berries, and oranges are high in fiber. Vegetables like broccoli, spinach, and cucumbers also have a lot of fiber. Maybe I can add some fiber supplements if I don't feel enough from my diet alone.

Next, the assistant suggested staying hydrated. I think drinking plenty of water is crucial, but sometimes I forget to drink enough. Maybe I can set a goal to drink 8 glasses a day. I also heard that water helps soften stools, so that's a good point. I should also avoid carbonated drinks and caffeine because they can make stools harder. I usually drink a lot of coffee, so

- After: For mild constipation, try drinking plenty of fluids, eating a balanced diet rich in fiber, and exercising regularly. You can also try taking a stool softener or a fiber supplement to help relieve constipation. If your symptoms persist or worsen, or if you experience severe abdominal pain, blood in your stool, or difficulty breathing, seek medical attention.


**Q: Is it normal to feel very tired with a cold?**

- Before: Okay, so I'm feeling really tired with a cold. I'm not sure if it's normal, but I want to figure this out. Let me think about how my cold is acting. I have a stuffy nose, maybe a little runny nose, and my throat feels a bit scratchy. I'm not sneezing much, but I do have a little cough sometimes. My energy level is dropping, and I'm not sleeping as well as I should. I feel like I'm just floating around all the time.

Hmm, when I get a cold, usually I feel better within a few days, right? But this time, I'm feeling worse. Maybe my body is fighting off the cold, but it's also getting me down. I wonder if it's the same for others. I've heard people say they feel really tired during flu season, but I'm not sure if that's the same as getting a cold.

I should consider other factors. Am I eating

- After: Yes, it's quite common to feel very tired when you have a cold. Your body's main concern is fighting off the virus, and it can take a toll on your energy levels. Rest, fluids, and a good sleep can help you get through the fatigue. If you're still feeling very tired or experiencing other concerning symptoms, don't hesitate to see a doctor.